# Generated by Django 6.0.6 on 2026-07-09 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('USER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('USER_ROLE', models.CharField(choices=[('explorer', 'Explorer'), ('merchant', 'Merchant'), ('admin', 'Admin')], max_length=20)),
                ('USER_STATUS', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('USER_EMAIL', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='USER_PASSWORD', max_length=128)),
                ('USER_FNAME', models.CharField(max_length=50)),
                ('USER_LNAME', models.CharField(max_length=50)),
                ('USER_MI', models.CharField(blank=True, max_length=1, null=True)),
                ('USER_GENDER', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('USER_IS_VERIFIED', models.BooleanField(default=False)),
                ('USER_REPUTATION', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('last_login', models.DateTimeField(blank=True, db_column='USER_LAST_LOGIN_AT', null=True)),
                ('USER_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('USER_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
