# Generated by Django 6.0.6 on 2026-07-04 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('USER_ROLE', models.CharField(choices=[('explorer', 'Explorer'), ('merchant', 'Merchant'), ('admin', 'Admin')], max_length=20)),
                ('USER_EMAIL', models.EmailField(max_length=100, unique=True)),
                ('USER_PASSWORD', models.CharField(max_length=255)),
                ('USER_FNAME', models.CharField(max_length=50)),
                ('USER_LNAME', models.CharField(max_length=50)),
                ('USER_MI', models.CharField(blank=True, max_length=1, null=True)),
                ('USER_GENDER', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('USER_IS_VERIFIED', models.BooleanField(default=False)),
                ('USER_IS_ACTIVE', models.BooleanField(default=True)),
                ('USER_REPUTATION', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('USER_LAST_LOGIN_AT', models.DateTimeField(blank=True, null=True)),
                ('USER_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('USER_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
