# Generated by Django 6.0.6 on 2026-07-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='USER_PASSWORD', max_length=128),
        ),
    ]
