# Generated by Django 6.0.6 on 2026-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='USER_ROLE',
            field=models.CharField(choices=[('explorer', 'Explorer'), ('merchant', 'Merchant'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], max_length=20),
        ),
    ]
