# Generated by Django 6.0.6 on 2026-07-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='HAS_COMPLETED_INTEREST_SELECTION',
            field=models.BooleanField(default=False),
        ),
    ]
