# Generated by Django 6.0.6 on 2026-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_has_completed_interest_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EMAIL_VERIFIED',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='EMAIL_VERIFIED_AT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
