# Generated by Django 6.0.6 on 2026-07-19 15:48


from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_super_admin(apps, schema_editor):
    User = apps.get_model("users", "User")

    email = "superadmin@gmail.com"

    if User.objects.filter(USER_EMAIL=email).exists():
        return

    user = User(
        USER_EMAIL=email,
        USER_FNAME="Super",
        USER_LNAME="Admin",
        USER_ROLE="super_admin",
        USER_STATUS="active",
        EMAIL_VERIFIED=True,
        USER_IS_VERIFIED=True,
        is_staff=True,
        is_superuser=True,
        password=make_password("admin1234"),  # Set a secure password for the super admin
    )


    user.save()


def delete_super_admin(apps, schema_editor):
    User = apps.get_model("users", "User")

    User.objects.filter(
        USER_EMAIL="superadmin@gmail.com"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified_user_email_verified_at'),
    ]

    operations = [
        migrations.RunPython(
            create_super_admin,
            delete_super_admin,
        ),
    ]