# Generated by Django 6.0.6 on 2026-07-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified_user_email_verified_at'),
    ]

    # Fresh environments provision Super Admins interactively with
    # ``manage.py createsuperuser``. Migration 0015 remediates databases
    # where the former bootstrap account was already created.
    operations = []
