# Generated by Django 6.0.6 on 2026-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_create_initial_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USER_PROFILE_PICTURE',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
