# Generated by Django 6.0.6 on 2026-07-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USER_PROFILE_PICTURE_PUBLIC_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
