# Generated by Django 6.0.6 on 2026-07-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_user_profile_picture_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USER_USE_OAUTH_AVATAR',
            field=models.BooleanField(default=True),
        ),
    ]
