# Generated by Django 6.0.6 on 2026-07-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_user_use_oauth_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='USER_GENDER',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
