# Generated by Django 6.0.6 on 2026-07-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='USER_GENDER',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
