# Generated by Django 6.0.6 on 2026-09-08 16:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def populate_null_user_reputations(
    apps,
    schema_editor,
):
    del schema_editor

    User = apps.get_model(
        "users",
        "User",
    )

    User.objects.filter(
        USER_REPUTATION__isnull=True,
    ).update(
        USER_REPUTATION=Decimal("0.20"),
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth",
            "0012_alter_user_first_name_max_length",
        ),
        (
            "users",
            "0010_alter_user_user_gender",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReputationEvent",
            fields=[
                (
                    "REVT_ID",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "REVT_EVENT_TYPE",
                    models.CharField(
                        choices=[
                            (
                                "vouch_reward",
                                "Vouch reward",
                            ),
                            (
                                "review_reward",
                                "Review reward",
                            ),
                            (
                                "review_with_photo_reward",
                                "Review with photo reward",
                            ),
                            (
                                "approved_report_reward",
                                "Approved report reward",
                            ),
                            (
                                "confirmed_violation_penalty",
                                "Confirmed violation penalty",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "REVT_APPLIED_CHANGE",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-1.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "REVT_RESULTING_REPUTATION",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "REVT_SOURCE_TYPE",
                    models.CharField(
                        choices=[
                            (
                                "business_vouch",
                                "Business vouch",
                            ),
                            (
                                "business_review",
                                "Business review",
                            ),
                            (
                                "review_report",
                                "Review report",
                            ),
                            (
                                "confirmed_review_violation",
                                "Confirmed review violation",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "REVT_SOURCE_ID",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "REVT_CREATED_AT",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
            ],
            options={
                "db_table": "REPUTATION_EVENT",
                "ordering": [
                    "-REVT_CREATED_AT",
                ],
            },
        ),
        migrations.RunPython(
            populate_null_user_reputations,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="USER_REPUTATION",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.20"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "USER_REPUTATION__gte",
                        Decimal("0.00"),
                    ),
                    (
                        "USER_REPUTATION__lte",
                        Decimal("1.00"),
                    ),
                ),
                name="user_reputation_between_zero_and_one",
            ),
        ),
        migrations.AddField(
            model_name="reputationevent",
            name="USER_ID",
            field=models.ForeignKey(
                db_column="USER_ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reputation_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="reputationevent",
            constraint=models.UniqueConstraint(
                fields=(
                    "REVT_SOURCE_TYPE",
                    "REVT_SOURCE_ID",
                ),
                name="unique_reputation_event_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="reputationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "REVT_APPLIED_CHANGE__gte",
                        Decimal("-1.00"),
                    ),
                    (
                        "REVT_APPLIED_CHANGE__lte",
                        Decimal("1.00"),
                    ),
                ),
                name="reputation_event_change_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="reputationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "REVT_RESULTING_REPUTATION__gte",
                        Decimal("0.00"),
                    ),
                    (
                        "REVT_RESULTING_REPUTATION__lte",
                        Decimal("1.00"),
                    ),
                ),
                name="reputation_event_result_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="reputationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "REVT_SOURCE_ID__gte",
                        1,
                    ),
                ),
                name="reputation_event_source_id_positive",
            ),
        ),
    ]
