# Generated by Django 6.0.6 on 2026-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='USER_USE_OAUTH_AVATAR',
        ),
        migrations.AddField(
            model_name='user',
            name='USER_AVATAR_KEY',
            field=models.CharField(
                blank=True,
                choices=[
                    ('explorer_avatar_1', 'Explorer avatar 1'),
                    ('explorer_avatar_2', 'Explorer avatar 2'),
                    ('explorer_avatar_3', 'Explorer avatar 3'),
                    ('explorer_avatar_4', 'Explorer avatar 4'),
                    ('explorer_avatar_5', 'Explorer avatar 5'),
                    ('explorer_avatar_6', 'Explorer avatar 6'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
