# Generated by Django 6.0.6 on 2026-08-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme', '0002_alter_msmespecialtytag_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtytag',
            name='TAG_COLOR',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('red', 'Red'), ('teal', 'Teal')], default='blue', max_length=20),
        ),
    ]
