import {
  Utensils,
  Coffee,
  ShoppingBag,
  Store,
  BedDouble,
  Hotel,
  Landmark,
  Church,
  Palmtree,
  Waves,
  Mountain,
  Trees,
  Compass,
  MapPinned,
  Camera,
  Music,
  Ticket,
  Dumbbell,
  HeartPulse,
  Sparkles,
  Palette,
  BookOpen,
  GraduationCap,
  BriefcaseBusiness,
  Car,
  Bus,
  Bike,
  Ship,
  PawPrint,
  Leaf,
} from "lucide-react";

export const CLUSTER_ICONS = [
  { value: "utensils", label: "Food & Dining", icon: Utensils },
  { value: "coffee", label: "Cafés & Coffee Shops", icon: Coffee },
  { value: "shopping_bag", label: "Shopping", icon: ShoppingBag },
  { value: "store", label: "Retail & Stores", icon: Store },
  { value: "bed_double", label: "Accommodation", icon: BedDouble },
  { value: "hotel", label: "Hotels & Lodging", icon: Hotel },
  { value: "landmark", label: "Landmarks & Attractions", icon: Landmark },
  { value: "church", label: "Religious & Heritage", icon: Church },
  { value: "tree_palm", label: "Beaches & Tropical", icon: Palmtree },
  { value: "waves", label: "Water Activities", icon: Waves },
  { value: "mountain", label: "Outdoor & Adventure", icon: Mountain },
  { value: "trees", label: "Nature & Eco-Tourism", icon: Trees },
  { value: "compass", label: "Tours & Exploration", icon: Compass },
  { value: "map_pinned", label: "Tourist Destinations", icon: MapPinned },
  { value: "camera", label: "Photography", icon: Camera },
  { value: "music", label: "Music & Nightlife", icon: Music },
  { value: "ticket", label: "Entertainment", icon: Ticket },
  { value: "dumbbell", label: "Fitness & Recreation", icon: Dumbbell },
  { value: "heart_pulse", label: "Wellness & Health", icon: HeartPulse },
  { value: "sparkles", label: "Beauty & Personal Care", icon: Sparkles },
  { value: "palette", label: "Arts & Crafts", icon: Palette },
  { value: "book_open", label: "Education & Learning", icon: BookOpen },
  {
    value: "graduation_cap",
    label: "Educational Services",
    icon: GraduationCap,
  },
  {
    value: "briefcase_business",
    label: "Professional Services",
    icon: BriefcaseBusiness,
  },
  { value: "car", label: "Automotive & Transport", icon: Car },
  { value: "bus", label: "Transportation", icon: Bus },
  { value: "bike", label: "Cycling & Rentals", icon: Bike },
  { value: "ship", label: "Marine & Island Services", icon: Ship },
  { value: "paw_print", label: "Pet Services", icon: PawPrint },
  { value: "leaf", label: "Local & Sustainable Products", icon: Leaf },
];
