# Generated by Django 6.0.6 on 2026-09-12 12:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JeepneyRoute',
            fields=[
                ('JRT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('JRT_CODE', models.CharField(max_length=10, unique=True)),
                ('JRT_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('JRT_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'JEEPNEY_ROUTE',
            },
        ),
        migrations.CreateModel(
            name='TransitPoint',
            fields=[
                ('TRPT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TRPT_NAME', models.CharField(max_length=150)),
                ('TRPT_POINT', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('TRPT_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('TRPT_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TRANSIT_POINT',
            },
        ),
        migrations.CreateModel(
            name='JeepneyRouteVariant',
            fields=[
                ('JRV_ID', models.AutoField(primary_key=True, serialize=False)),
                ('JRV_GEOMETRY', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('JRV_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('JRV_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('JRT_ID', models.ForeignKey(db_column='JRT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='transit.jeepneyroute')),
                ('JRV_DESTINATION_ID', models.ForeignKey(db_column='JRV_DESTINATION_ID', on_delete=django.db.models.deletion.PROTECT, related_name='terminating_route_variants', to='transit.transitpoint')),
                ('JRV_ORIGIN_ID', models.ForeignKey(db_column='JRV_ORIGIN_ID', on_delete=django.db.models.deletion.PROTECT, related_name='originating_route_variants', to='transit.transitpoint')),
            ],
            options={
                'db_table': 'JEEPNEY_ROUTE_VARIANT',
            },
        ),
        migrations.CreateModel(
            name='TransitTransfer',
            fields=[
                ('TTFR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TTFR_STATUS', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('TTFR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('TTFR_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('TTFR_FROM_TRANSIT_POINT_ID', models.ForeignKey(db_column='TTFR_FROM_TRANSIT_POINT_ID', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='transit.transitpoint')),
                ('TTFR_FROM_VARIANT_ID', models.ForeignKey(db_column='TTFR_FROM_VARIANT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='transit.jeepneyroutevariant')),
                ('TTFR_TO_TRANSIT_POINT_ID', models.ForeignKey(db_column='TTFR_TO_TRANSIT_POINT_ID', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='transit.transitpoint')),
                ('TTFR_TO_VARIANT_ID', models.ForeignKey(db_column='TTFR_TO_VARIANT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='transit.jeepneyroutevariant')),
            ],
            options={
                'db_table': 'TRANSIT_TRANSFER',
            },
        ),
        migrations.CreateModel(
            name='RouteTransitPoint',
            fields=[
                ('RVTP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('RVTP_SEQUENCE', models.PositiveIntegerField()),
                ('RVTP_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('RVTP_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('JRV_ID', models.ForeignKey(db_column='JRV_ID', on_delete=django.db.models.deletion.CASCADE, related_name='route_transit_points', to='transit.jeepneyroutevariant')),
                ('TRPT_ID', models.ForeignKey(db_column='TRPT_ID', on_delete=django.db.models.deletion.PROTECT, related_name='route_memberships', to='transit.transitpoint')),
            ],
            options={
                'db_table': 'ROUTE_TRANSIT_POINT',
                'ordering': ['JRV_ID', 'RVTP_SEQUENCE'],
                'constraints': [models.UniqueConstraint(fields=('JRV_ID', 'RVTP_SEQUENCE'), name='unique_route_variant_sequence'), models.UniqueConstraint(fields=('JRV_ID', 'TRPT_ID'), name='unique_route_variant_transit_point'), models.CheckConstraint(condition=models.Q(('RVTP_SEQUENCE__gte', 1)), name='route_transit_point_sequence_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='jeepneyroutevariant',
            constraint=models.UniqueConstraint(fields=('JRT_ID', 'JRV_ORIGIN_ID', 'JRV_DESTINATION_ID'), name='unique_jeepney_route_direction'),
        ),
        migrations.AddConstraint(
            model_name='jeepneyroutevariant',
            constraint=models.CheckConstraint(condition=models.Q(('JRV_ORIGIN_ID', models.F('JRV_DESTINATION_ID')), _negated=True), name='route_variant_distinct_endpoints'),
        ),
        migrations.AddIndex(
            model_name='transittransfer',
            index=models.Index(fields=['TTFR_STATUS'], name='transit_transfer_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='transittransfer',
            constraint=models.UniqueConstraint(fields=('TTFR_FROM_VARIANT_ID', 'TTFR_TO_VARIANT_ID', 'TTFR_FROM_TRANSIT_POINT_ID', 'TTFR_TO_TRANSIT_POINT_ID'), name='unique_transit_transfer_connection'),
        ),
        migrations.AddConstraint(
            model_name='transittransfer',
            constraint=models.CheckConstraint(condition=models.Q(('TTFR_FROM_VARIANT_ID', models.F('TTFR_TO_VARIANT_ID')), _negated=True), name='transit_transfer_distinct_variants'),
        ),
    ]
