# Generated by Django 6.0.6 on 2026-08-03 11:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  
        migrations.CreateModel(
            name='MerchantApplication',
            fields=[
                ('MAPP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MAPP_STATUS', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('MAPP_CURRENT_STEP', models.PositiveIntegerField(default=1)),
                ('MAPP_HIGHEST_COMPLETED_STEP', models.PositiveIntegerField(default=0)),
                ('MAPP_SUBMITTED_AT', models.DateTimeField(blank=True, null=True)),
                ('MAPP_REVIEWED_AT', models.DateTimeField(blank=True, null=True)),
                ('MAPP_REJECTION_REASON', models.TextField(blank=True, null=True)),
                ('MAPP_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MAPP_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='merchant_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MERCHANT_APPLICATION',
            },
        ),
        migrations.CreateModel(
            name='MerchantApplicationDocument',
            fields=[
                ('MDOC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MDOC_DOCUMENT_TYPE', models.CharField(choices=[('businessRegistration', 'Business Registration'), ('authorizationDocument', 'Authorization Document'), ('additionalDocuments', 'Additional Documents')], max_length=30)),
                ('MDOC_DOCUMENT_URL', models.URLField()),
                ('MDOC_DOCUMENT_PUBLIC_ID', models.CharField(max_length=255)),
                ('MDOC_FILE_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('MDOC_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MDOC_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('MAPP_ID', models.ForeignKey(db_column='MAPP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='merchant_application.merchantapplication')),
            ],
            options={
                'db_table': 'MERCHANT_APPLICATION_DOCUMENT',
            },
        ),
        migrations.CreateModel(
            name='MerchantApplicationIdentity',
            fields=[
                ('MIDN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MIDN_BUSINESS_NAME', models.CharField(max_length=150)),
                ('MIDN_BUSINESS_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('MIDN_CONTACT_NUMBER', models.CharField(max_length=20)),
                ('MIDN_BUSINESS_EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('MIDN_WEBSITE', models.URLField(blank=True, null=True)),
                ('MIDN_REPRESENTATIVE_NAME', models.CharField(max_length=150)),
                ('MIDN_REPRESENTATIVE_ROLE', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('authorized_representative', 'Authorized Representative'), ('other', 'Other')], max_length=30)),
                ('MIDN_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MIDN_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('CLUS_ID', models.ForeignKey(db_column='CLUS_ID', on_delete=django.db.models.deletion.PROTECT, related_name='merchant_application_identities', to='business.cluster')),
                ('CTGRY_ID', models.ForeignKey(db_column='CTGRY_ID', on_delete=django.db.models.deletion.PROTECT, related_name='merchant_application_identities', to='business.category')),
                ('MAPP_ID', models.OneToOneField(db_column='MAPP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='merchant_application.merchantapplication')),
                ('specialty_tags', models.ManyToManyField(blank=True, related_name='merchant_application_identities', to='business.specialtytag')),
            ],
            options={
                'db_table': 'MERCHANT_APPLICATION_IDENTITY',
            },
        ),
        migrations.CreateModel(
            name='MerchantApplicationLocation',
            fields=[
                ('MLOC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MLOC_PROVINCE', models.CharField(max_length=100)),
                ('MLOC_CITY', models.CharField(max_length=100)),
                ('MLOC_BARANGAY', models.CharField(max_length=100)),
                ('MLOC_STREET_ADDRESS', models.CharField(max_length=255)),
                ('MLOC_UNIT', models.CharField(blank=True, max_length=100, null=True)),
                ('MLOC_POINT', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('MLOC_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MLOC_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('MAPP_ID', models.OneToOneField(db_column='MAPP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='merchant_application.merchantapplication')),
            ],
            options={
                'db_table': 'MERCHANT_APPLICATION_LOCATION',
            },
        ),
        migrations.CreateModel(
            name='MerchantApplicationLandmark',
            fields=[
                ('MLMK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MLMK_NAME', models.CharField(max_length=150)),
                ('MLMK_ADDRESS', models.CharField(max_length=255)),
                ('MLMK_POINT', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('MLMK_SOURCE', models.CharField(choices=[('google', 'Google'), ('custom', 'Custom')], max_length=10)),
                ('MLMK_PLACE_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('MLMK_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MLMK_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('MLOC_ID', models.ForeignKey(db_column='MLOC_ID', on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='merchant_application.merchantapplicationlocation')),
            ],
            options={
                'db_table': 'MERCHANT_APPLICATION_LANDMARK',
            },
        ),
        migrations.CreateModel(
            name='MerchantApplicationPhotos',
            fields=[
                ('MPHT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MPHT_CATEGORY', models.CharField(choices=[('storefront', 'Storefront'), ('interior', 'Interior'), ('products', 'Products'), ('additional', 'Additional')], max_length=20)),
                ('MPHT_PHOTO_URL', models.URLField()),
                ('MPHT_PHOTO_PUBLIC_ID', models.CharField(max_length=255)),
                ('MPHT_FILE_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('MPHT_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MPHT_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('MAPP_ID', models.ForeignKey(db_column='MAPP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='merchant_application.merchantapplication')),
            ],
            options={
                'db_table': 'MERCHANT_APPLICATION_PHOTO',
            },
        ),
        migrations.CreateModel(
            name='MerchantApplicationOperatingHours',
            fields=[
                ('MHRS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MHRS_DAY', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('MHRS_IS_OPEN', models.BooleanField(default=True)),
                ('MHRS_IS_24_HOURS', models.BooleanField(default=False)),
                ('MHRS_OPEN_TIME', models.TimeField(blank=True, null=True)),
                ('MHRS_CLOSE_TIME', models.TimeField(blank=True, null=True)),
                ('MHRS_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MHRS_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('MAPP_ID', models.ForeignKey(db_column='MAPP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='merchant_application.merchantapplication')),
            ],
            options={
                'db_table': 'MERCHANT_APPLICATION_OPERATING_HOURS',
                'unique_together': {('MAPP_ID', 'MHRS_DAY')},
            },
        ),
    ]
