# Generated by Django 6.0.6 on 2026-08-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantapplicationdocument',
            name='MDOC_DOCUMENT_TYPE',
            field=models.CharField(choices=[('business_registration', 'Business Registration'), ('authorization_document', 'Authorization Document'), ('additional_documents', 'Additional Documents')], max_length=30),
        ),
    ]
