# Generated by Django 6.0.6 on 2026-08-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_application', '0002_alter_merchantapplicationdocument_mdoc_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantapplication',
            name='MAPP_CURRENT_STEP',
        ),
    ]
