# Generated by Django 6.0.6 on 2026-08-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_application', '0003_remove_merchantapplication_mapp_current_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantApplicationFeedback',
            fields=[
                ('MAPF_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MAPF_SECTION', models.CharField(choices=[('identity', 'Business Identity'), ('location', 'Business Location'), ('operating_hours', 'Operating Hours'), ('photos', 'Business Photos'), ('documents', 'Verification Documents')], max_length=30)),
                ('MAPF_MESSAGE', models.TextField()),
                ('MAPF_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MAPP_ID', models.ForeignKey(db_column='MAPP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='merchant_application.merchantapplication')),
            ],
            options={
                'db_table': 'MERCHANT_APPLICATION_FEEDBACK',
            },
        ),
    ]
