# Generated by Django 6.0.6 on 2026-08-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_application', '0005_merchantapplication_unique_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapplication',
            name='MAPP_SUBMISSION_COUNT',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
