# Generated by Django 6.0.6 on 2026-08-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_application', '0007_merchantapplicationreview_feedback_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantapplicationfeedback',
            options={'ordering': ['MAPF_CREATED_AT']},
        ),
        migrations.RemoveField(
            model_name='merchantapplication',
            name='MAPP_REJECTION_REASON',
        ),
    ]
