# Generated by Django 6.0.6 on 2026-08-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_application', '0008_alter_merchantapplicationfeedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapplication',
            name='MAPP_DOCUMENTS_UPDATED_AT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='MAPP_IDENTITY_UPDATED_AT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='MAPP_LOCATION_UPDATED_AT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='MAPP_OPERATING_HOURS_UPDATED_AT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantapplication',
            name='MAPP_PHOTOS_UPDATED_AT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
