# Generated by Django 6.0.6 on 2026-08-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_application', '0009_merchantapplication_mapp_documents_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapplicationdocument',
            name='MDOC_CLOUDINARY_VERSION',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
