# Generated by Django 6.0.6 on 2026-08-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_application', '0010_merchantapplicationdocument_mdoc_cloudinary_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantApplicationSubmission',
            fields=[
                ('MASUB_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MASUB_SUBMISSION_NUMBER', models.PositiveIntegerField()),
                ('MASUB_SUBMITTED_AT', models.DateTimeField()),
                ('MAPP_ID', models.ForeignKey(db_column='MAPP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='merchant_application.merchantapplication')),
            ],
            options={
                'db_table': 'MERCHANT_APPLICATION_SUBMISSION',
                'ordering': ['MASUB_SUBMISSION_NUMBER'],
            },
        ),
        migrations.AddField(
            model_name='merchantapplicationreview',
            name='MASUB_ID',
            field=models.OneToOneField(blank=True, db_column='MASUB_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='merchant_application.merchantapplicationsubmission'),
        ),
        migrations.AddConstraint(
            model_name='merchantapplicationsubmission',
            constraint=models.UniqueConstraint(fields=('MAPP_ID', 'MASUB_SUBMISSION_NUMBER'), name='unique_application_submission_number'),
        ),
    ]
