# Generated by Django 6.0.6 on 2026-08-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_merge_0007_cluster_clus_icon_0007_serviceableboundary'),
        ('merchant_application', '0013_backfill_review_sla_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapplication',
            name='BUSN_ID',
            field=models.OneToOneField(blank=True, db_column='BUSN_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_application', to='business.business'),
        ),
    ]
