# Generated by Django 6.0.6 on 2026-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_application', '0014_merchantapplication_busn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapplication',
            name='MAPP_MERCHANT_MODE_ACKNOWLEDGED',
            field=models.BooleanField(default=False),
        ),
    ]
