# Generated by Django 6.0.6 on 2026-09-02 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0021_businessspecialtytag_bst_vouch_count'),
        ('reviews', '0005_replytemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantReviewDispute',
            fields=[
                ('MRDSP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MRDSP_REASON', models.CharField(choices=[('fake_review', 'Fake or fabricated review'), ('did_not_visit', 'Reviewer did not visit the business'), ('abusive_content', 'Abusive or inappropriate content'), ('misleading_information', 'Misleading information'), ('conflict_of_interest', 'Conflict of interest'), ('other', 'Other')], max_length=30)),
                ('MRDSP_DESCRIPTION', models.TextField(max_length=2000)),
                ('MRDSP_STATUS', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('MRDSP_ADMIN_NOTES', models.TextField(blank=True, null=True)),
                ('MRDSP_RESOLVED_AT', models.DateTimeField(blank=True, null=True)),
                ('MRDSP_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MRDSP_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='review_disputes', to='business.business')),
                ('REVW_ID', models.ForeignKey(db_column='REVW_ID', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_disputes', to='reviews.review')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_review_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MERCHANT_REVIEW_DISPUTE',
                'ordering': ['-MRDSP_CREATED_AT'],
            },
        ),
        migrations.CreateModel(
            name='MerchantReviewDisputeEvidence',
            fields=[
                ('MRDSE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MRDSE_TYPE', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('MRDSE_URL', models.URLField(max_length=1000)),
                ('MRDSE_PUBLIC_ID', models.CharField(max_length=255)),
                ('MRDSE_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MRDSP_ID', models.ForeignKey(db_column='MRDSP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='review_disputes.merchantreviewdispute')),
            ],
            options={
                'db_table': 'MERCHANT_REVIEW_DISPUTE_EVIDENCE',
                'ordering': ['MRDSE_CREATED_AT'],
            },
        ),
        migrations.AddConstraint(
            model_name='merchantreviewdispute',
            constraint=models.UniqueConstraint(condition=models.Q(('MRDSP_STATUS__in', ['pending', 'under_review'])), fields=('REVW_ID',), name='unique_active_dispute_per_review'),
        ),
    ]
