# Generated by Django 6.0.6 on 2026-09-04 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_businessspecialtytag_bst_vouch_count'),
        ('review_disputes', '0001_initial'),
        ('reviews', '0005_replytemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='merchantreviewdispute',
            name='unique_active_dispute_per_review',
        ),
        migrations.AlterField(
            model_name='merchantreviewdispute',
            name='MRDSP_STATUS',
            field=models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='merchantreviewdispute',
            constraint=models.UniqueConstraint(condition=models.Q(('MRDSP_STATUS', 'pending')), fields=('REVW_ID',), name='unique_active_dispute_per_review'),
        ),
    ]
