# Generated by Django 6.0.6 on 2026-09-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_disputes', '0002_remove_merchantreviewdispute_unique_active_dispute_per_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantreviewdisputeevidence',
            name='MRDSE_FILE_NAME',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
