# Generated by Django 6.0.6 on 2026-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_disputes', '0003_merchantreviewdisputeevidence_mrdse_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantreviewdispute',
            name='MRDSP_REASON',
            field=models.CharField(choices=[('fake_review', 'Fake or non-genuine review'), ('abusive_content', 'Abusive or inappropriate content'), ('misleading_information', 'False or materially misleading information'), ('conflict_of_interest', 'Conflict of interest'), ('wrong_business', 'Review is about another business or unrelated experience'), ('other', 'Other')], max_length=30),
        ),
    ]
