# Generated by Django 6.0.6 on 2026-07-18 18:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('CLUS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CLUS_NAME', models.CharField(max_length=100, unique=True)),
                ('CLUS_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('CLUS_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('CLUS_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CLUSTER',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LOCT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('LOCT_POINT', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('LOCT_ADDRESS', models.CharField(max_length=255)),
                ('LOCT_CITY', models.CharField(default='Cebu City', max_length=100)),
                ('LOCT_PROVINCE', models.CharField(default='Cebu', max_length=100)),
                ('LOCT_POSTAL_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('LOCT_STATUS', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('LOCT_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('LOCT_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LOCATION',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyTag',
            fields=[
                ('TAG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TAG_NAME', models.CharField(max_length=100, unique=True)),
                ('TAG_TIER', models.PositiveSmallIntegerField()),
                ('TAG_WEIGHT', models.PositiveSmallIntegerField()),
                ('TAG_IS_PREDEFINED', models.BooleanField(default=True)),
                ('TAG_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('TAG_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SPECIALTY_TAG',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CTGRY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CTGRY_NAME', models.CharField(max_length=100)),
                ('CTGRY_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('CTGRY_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('CTGRY_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('CLUS_ID', models.ForeignKey(db_column='CLUS_ID', on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='msme.cluster')),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Msme',
            fields=[
                ('MSME_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MSME_NAME', models.CharField(max_length=150)),
                ('MSME_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('MSME_STATUS', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('MSME_IS_VERIFIED', models.BooleanField(default=False)),
                ('MSME_VOUCH_COUNT', models.PositiveIntegerField(default=0)),
                ('MSME_REVIEW_COUNT', models.PositiveIntegerField(default=0)),
                ('MSME_POCKET_COUNT', models.PositiveIntegerField(default=0)),
                ('MSME_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MSME_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('CTGRY_ID', models.ForeignKey(db_column='CTGRY_ID', on_delete=django.db.models.deletion.PROTECT, related_name='msmes', to='msme.category')),
                ('LOC_ID', models.ForeignKey(db_column='LOC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='msmes', to='msme.location')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='owned_msmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MSME',
            },
        ),
        migrations.CreateModel(
            name='DiscoveryScore',
            fields=[
                ('DSC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DSC_S_SCORE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DSC_V_SCORE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DSC_D_SCORE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DSC_IS_CURRENT', models.BooleanField(default=True)),
                ('DSC_COMPUTED_AT', models.DateTimeField()),
                ('DSC_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('DSC_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('MSME_ID', models.ForeignKey(db_column='MSME_ID', on_delete=django.db.models.deletion.CASCADE, related_name='discovery_scores', to='msme.msme')),
            ],
            options={
                'db_table': 'DISCOVERY_SCORE',
                'ordering': ['-DSC_COMPUTED_AT'],
            },
        ),
        migrations.CreateModel(
            name='MsmeSpecialtyTag',
            fields=[
                ('MTAG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MTAG_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('MTAG_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('MSME_ID', models.ForeignKey(db_column='MSME_ID', on_delete=django.db.models.deletion.CASCADE, related_name='specialty_tags', to='msme.msme')),
                ('TAG_ID', models.ForeignKey(db_column='TAG_ID', on_delete=django.db.models.deletion.PROTECT, related_name='msme_links', to='msme.specialtytag')),
            ],
            options={
                'db_table': 'MSME_SPECIALTY_TAG',
                'unique_together': {('MSME_ID', 'TAG_ID')},
            },
        ),
    ]
