# Generated by Django 6.0.6 on 2026-08-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='msmespecialtytag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='specialtytag',
            name='TAG_IS_PREDEFINED',
        ),
        migrations.RemoveField(
            model_name='specialtytag',
            name='TAG_TIER',
        ),
        migrations.RemoveField(
            model_name='specialtytag',
            name='TAG_WEIGHT',
        ),
        migrations.AddField(
            model_name='msme',
            name='SPECIALTY_TAGS',
            field=models.ManyToManyField(blank=True, related_name='msmes', through='business.MsmeSpecialtyTag', to='business.specialtytag'),
        ),
        migrations.AlterField(
            model_name='msmespecialtytag',
            name='MSME_ID',
            field=models.ForeignKey(db_column='MSME_ID', on_delete=django.db.models.deletion.CASCADE, related_name='specialty_tag_links', to='business.msme'),
        ),
        migrations.AddConstraint(
            model_name='msmespecialtytag',
            constraint=models.UniqueConstraint(fields=('MSME_ID', 'TAG_ID'), name='unique_msme_specialty_tag'),
        ),
    ]
