# Generated by Django 6.0.6 on 2026-08-09 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_rename_msme_to_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessspecialtytag',
            name='unique_msme_specialty_tag',
        ),
        migrations.AlterField(
            model_name='business',
            name='CTGRY_ID',
            field=models.ForeignKey(db_column='CTGRY_ID', on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='business.category'),
        ),
        migrations.AlterField(
            model_name='business',
            name='LOC_ID',
            field=models.ForeignKey(db_column='LOC_ID', on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='business.location'),
        ),
        migrations.AlterField(
            model_name='business',
            name='SPECIALTY_TAGS',
            field=models.ManyToManyField(blank=True, related_name='businesses', through='business.BusinessSpecialtyTag', to='business.specialtytag'),
        ),
        migrations.AlterField(
            model_name='business',
            name='USER_ID',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessspecialtytag',
            name='TAG_ID',
            field=models.ForeignKey(db_column='TAG_ID', on_delete=django.db.models.deletion.PROTECT, related_name='business_links', to='business.specialtytag'),
        ),
        migrations.AddConstraint(
            model_name='businessspecialtytag',
            constraint=models.UniqueConstraint(fields=('MSME_ID', 'TAG_ID'), name='unique_business_specialty_tag'),
        ),
        migrations.AlterModelTable(
            name='business',
            table='BUSINESS',
        ),
        migrations.AlterModelTable(
            name='businessspecialtytag',
            table='BUSINESS_SPECIALTY_TAG',
        ),
    ]
