# Generated by Django 6.0.6 on 2026-08-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_msme_fields_to_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='CLUS_ICON',
            field=models.CharField(choices=[('utensils', 'Utensils'), ('coffee', 'Coffee'), ('shopping_bag', 'Shopping Bag'), ('store', 'Store'), ('bed_double', 'Bed Double'), ('hotel', 'Hotel'), ('landmark', 'Landmark'), ('church', 'Church'), ('tree_palm', 'Tree Palm'), ('waves', 'Waves'), ('mountain', 'Mountain'), ('trees', 'Trees'), ('compass', 'Compass'), ('map_pinned', 'Map Pinned'), ('camera', 'Camera'), ('music', 'Music'), ('ticket', 'Ticket'), ('dumbbell', 'Dumbbell'), ('heart_pulse', 'Heart Pulse'), ('sparkles', 'Sparkles'), ('palette', 'Palette'), ('book_open', 'Book Open'), ('graduation_cap', 'Graduation Cap'), ('briefcase_business', 'Briefcase Business'), ('car', 'Car'), ('bus', 'Bus'), ('bike', 'Bike'), ('ship', 'Ship'), ('paw_print', 'Paw Print'), ('leaf', 'Leaf')], default='utensils', max_length=50),
        ),
    ]
