# Generated by Django 6.0.6 on 2026-08-11 14:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_msme_fields_to_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceableBoundary',
            fields=[
                ('SBND_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SBND_NAME', models.CharField(max_length=100)),
                ('SBND_PSGC_CODE', models.CharField(blank=True, max_length=15, null=True)),
                ('SBND_BOUNDARY', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('SBND_IS_ACTIVE', models.BooleanField(default=True)),
                ('SBND_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('SBND_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SERVICEABLE_BOUNDARY',
            },
        ),
    ]
