# Generated by Django 6.0.6 on 2026-08-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_cluster_clus_icon'),
        ('business', '0007_serviceableboundary'),
    ]

    operations = [
    ]
