# Generated by Django 6.0.6 on 2026-08-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_merge_0007_cluster_clus_icon_0007_serviceableboundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='LOCT_STATUS',
        ),
        migrations.AlterField(
            model_name='business',
            name='BUSN_STATUS',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
