# Generated by Django 6.0.6 on 2026-08-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_location_loct_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPhoto',
            fields=[
                ('BPHO_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BPHO_CATEGORY', models.CharField(choices=[('storefront', 'Storefront'), ('interior', 'Interior'), ('products', 'Products'), ('additional', 'Additional')], max_length=20)),
                ('BPHO_PHOTO_URL', models.URLField()),
                ('BPHO_PHOTO_PUBLIC_ID', models.CharField(max_length=255)),
                ('BPHO_FILE_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('BPHO_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('BPHO_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='business.business')),
            ],
            options={
                'db_table': 'BUSINESS_PHOTO',
            },
        ),
        migrations.CreateModel(
            name='BusinessOperatingHours',
            fields=[
                ('BOHR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BOHR_DAY', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('BOHR_IS_OPEN', models.BooleanField(default=True)),
                ('BOHR_IS_24_HOURS', models.BooleanField(default=False)),
                ('BOHR_OPEN_TIME', models.TimeField(blank=True, null=True)),
                ('BOHR_CLOSE_TIME', models.TimeField(blank=True, null=True)),
                ('BOHR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('BOHR_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='business.business')),
            ],
            options={
                'db_table': 'BUSINESS_OPERATING_HOURS',
                'constraints': [models.UniqueConstraint(fields=('BUSN_ID', 'BOHR_DAY'), name='unique_business_operating_hours_day')],
            },
        ),
    ]
