# Generated by Django 6.0.6 on 2026-08-16 15:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_businessphoto_businessoperatinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLandmark',
            fields=[
                ('BLMK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BLMK_NAME', models.CharField(max_length=150)),
                ('BLMK_ADDRESS', models.CharField(max_length=255)),
                ('BLMK_POINT', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('BLMK_SOURCE', models.CharField(choices=[('google', 'Google'), ('custom', 'Custom')], max_length=10)),
                ('BLMK_PLACE_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('BLMK_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('BLMK_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('LOCT_ID', models.ForeignKey(db_column='LOCT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='business.location')),
            ],
            options={
                'db_table': 'BUSINESS_LANDMARK',
            },
        ),
    ]
