# Generated by Django 6.0.6 on 2026-08-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_rename_business_location_column'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="business",
                    name="LOCT_ID",
                    field=models.ForeignKey(
                        db_column="LOCT_ID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="businesses",
                        to="business.location",
                    ),
                ),
            ],
        ),
    ]
