# Generated by Django 6.0.6 on 2026-08-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_business_loct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='BUSN_COVER_PHOTO_PUBLIC_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='BUSN_COVER_PHOTO_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
