# Generated by Django 6.0.6 on 2026-08-22 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_business_busn_cover_photo_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='USER_ID',
            field=models.OneToOneField(db_column='USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='owned_business', to=settings.AUTH_USER_MODEL),
        ),
    ]
