# Generated by Django 6.0.6 on 2026-08-23 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('business', '0016_alter_business_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name='BusinessVouch',
            fields=[
                ('VOUCH_ID', models.AutoField(primary_key=True, serialize=False)),
                ('VOUCH_FLAG_SUSPICIOUS', models.BooleanField(default=False)),
                ('VOUCH_DEVICE_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('VOUCH_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('VOUCH_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='vouches', to='business.business')),
                ('TAG_ID', models.ForeignKey(db_column='TAG_ID', on_delete=django.db.models.deletion.CASCADE, related_name='vouches', to='business.specialtytag')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='business_vouches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BUSINESS_VOUCH',
                'constraints': [models.UniqueConstraint(fields=('BUSN_ID', 'USER_ID', 'TAG_ID'), name='unique_business_user_tag_vouch')],
            },
        ),
    ]
