# Generated by Django 6.0.6 on 2026-08-24 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_businessvouch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPocket',
            fields=[
                ('PCKT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PCKT_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PCKT_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='pocket_entries', to='business.business')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='business_pockets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BUSINESS_POCKET',
                'constraints': [models.UniqueConstraint(fields=('USER_ID', 'BUSN_ID'), name='unique_user_business_pocket')],
            },
        ),
    ]
