# Generated by Django 6.0.6 on 2026-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_businesspocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='BUSN_CONTACT_NUMBER',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='BUSN_EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='BUSN_WEBSITE',
            field=models.URLField(blank=True, null=True),
        ),
    ]
