# Generated by Django 6.0.6 on 2026-08-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_businesspocket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('REVW_ID', models.AutoField(primary_key=True, serialize=False)),
                ('REVW_TEXT', models.TextField(max_length=1000)),
                ('REVW_STATUS', models.CharField(choices=[('published', 'Published'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='published', max_length=20)),
                ('REVW_LIKE_COUNT', models.PositiveIntegerField(default=0)),
                ('REVW_REPORT_COUNT', models.PositiveIntegerField(default=0)),
                ('REVW_IS_SPAM_FLAGGED', models.BooleanField(default=False)),
                ('REVW_IS_OUTLIER_SENTIMENT', models.BooleanField(default=False)),
                ('REVW_DEVICE_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('REVW_IS_DEVICE_ABUSE_FLAGGED', models.BooleanField(default=False)),
                ('REVW_SENTIMENT_SCORE', models.FloatField(blank=True, null=True)),
                ('REVW_SENTIMENT_LABEL', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('REVW_MODERATION_NOTES', models.TextField(blank=True, null=True)),
                ('REVW_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('REVW_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.business')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='business_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BUSINESS_REVIEW',
                'ordering': ['-REVW_CREATED_AT'],
            },
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('RPHO_ID', models.AutoField(primary_key=True, serialize=False)),
                ('RPHO_PHOTO_URL', models.URLField()),
                ('RPHO_PHOTO_PUBLIC_ID', models.CharField(max_length=255)),
                ('REVW_ID', models.ForeignKey(db_column='REVW_ID', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='business.businessreview')),
            ],
            options={
                'db_table': 'REVIEW_PHOTO',
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('RPLY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('RPLY_TEXT', models.TextField(max_length=1000)),
                ('RPLY_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('RPLY_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('REVW_ID', models.OneToOneField(db_column='REVW_ID', on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='business.businessreview')),
            ],
            options={
                'db_table': 'REVIEW_REPLY',
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('RREP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('RREP_TYPE', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=30)),
                ('RREP_STATUS', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('RREP_DEVICE_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('RREP_FLAG_SUSPICIOUS', models.BooleanField(default=False)),
                ('RREP_NOTES', models.TextField(blank=True, null=True)),
                ('RREP_WITHDRAWN_AT', models.DateTimeField(blank=True, null=True)),
                ('RREP_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('RREP_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('REVW_ID', models.ForeignKey(db_column='REVW_ID', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='business.businessreview')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'REVIEW_REPORT',
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('RLIK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('RLIK_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('RLIK_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('REVW_ID', models.ForeignKey(db_column='REVW_ID', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='business.businessreview')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'REVIEW_LIKE',
                'constraints': [models.UniqueConstraint(fields=('REVW_ID', 'USER_ID'), name='unique_review_user_like')],
            },
        ),
    ]
