# Generated by Django 6.0.6 on 2026-08-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_business_busn_contact_number_business_busn_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='BUSN_CONTACT_NUMBER',
            field=models.CharField(max_length=20),
        ),
    ]
