# Generated by Django 6.0.6 on 2026-08-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_alter_business_busn_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessspecialtytag',
            name='BST_VOUCH_COUNT',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
