# Generated by Django 6.0.6 on 2026-09-09

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def initialize_legacy_vouch_evidence(
    apps,
    schema_editor,
):
    del schema_editor

    BusinessVouch = apps.get_model(
        "business",
        "BusinessVouch",
    )

    BusinessVouch.objects.all().update(
        VOUCH_REPUTATION_SNAPSHOT=Decimal("0.20"),
        VOUCH_EVIDENCE_IS_VALID=True,
        VOUCH_EVIDENCE_INVALIDATED_AT=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0022_businessspecialtytag_lifecycle",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="businessvouch",
            name="VOUCH_EVIDENCE_INVALIDATED_AT",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businessvouch",
            name="VOUCH_EVIDENCE_IS_VALID",
            field=models.BooleanField(
                default=True,
            ),
        ),
        migrations.AddField(
            model_name="businessvouch",
            name="VOUCH_REPUTATION_SNAPSHOT",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.20"),
                editable=False,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            initialize_legacy_vouch_evidence,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="businessvouch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "VOUCH_REPUTATION_SNAPSHOT__gte",
                        Decimal("0.00"),
                    ),
                    (
                        "VOUCH_REPUTATION_SNAPSHOT__lte",
                        Decimal("1.00"),
                    ),
                ),
                name="vouch_reputation_snapshot_in_range",
            ),
        ),
    ]
