# Generated by Django 6.0.6 on 2026-09-09

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0023_businessvouch_evidence_context",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="businessspecialtytag",
            name="BST_TAG_SCORE",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.00000"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="businessspecialtytag",
            name="BST_SCORE_UPDATED_AT",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="businessspecialtytag",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        BST_TAG_SCORE__gte=Decimal("0.00"),
                    )
                    & models.Q(
                        BST_TAG_SCORE__lte=Decimal("1.00"),
                    )
                ),
                name="business_specialty_tag_score_in_range",
            ),
        ),
    ]
