# Generated by Django 6.0.6 on 2026-09-09 15:06

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def preserve_current_discovery_scores(
    apps,
    _schema_editor,
):
    """Keeps one current or latest legacy score for each business."""

    discovery_score_model = apps.get_model(
        "business",
        "DiscoveryScore",
    )
    business_ids = list(
        discovery_score_model.objects
        .order_by()
        .values_list(
            "BUSN_ID_id",
            flat=True,
        )
        .distinct(),
    )

    for business_id in business_ids:
        business_scores = discovery_score_model.objects.filter(
            BUSN_ID_id=business_id,
        )
        retained_score = (
            business_scores
            .filter(
                DSC_IS_CURRENT=True,
            )
            .order_by(
                "-DSC_COMPUTED_AT",
                "-DSC_UPDATED_AT",
                "-DSC_ID",
            )
            .first()
        )

        if retained_score is None:
            retained_score = business_scores.order_by(
                "-DSC_COMPUTED_AT",
                "-DSC_UPDATED_AT",
                "-DSC_ID",
            ).first()

        business_scores.exclude(
            DSC_ID=retained_score.DSC_ID,
        ).delete()

        retained_score.DSC_S_SCORE = min(
            Decimal("1.00"),
            max(
                Decimal("0.00"),
                retained_score.DSC_S_SCORE,
            ),
        )
        retained_score.DSC_V_SCORE = min(
            Decimal("1.00"),
            max(
                Decimal("0.00"),
                retained_score.DSC_V_SCORE,
            ),
        )
        retained_score.DSC_D_SCORE = min(
            Decimal("1.00"),
            max(
                Decimal("0.00"),
                retained_score.DSC_D_SCORE,
            ),
        )
        retained_score.save(
            update_fields=[
                "DSC_S_SCORE",
                "DSC_V_SCORE",
                "DSC_D_SCORE",
            ],
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0024_businessspecialtytag_score_state",
        ),
    ]

    operations = [
        migrations.RunPython(
            preserve_current_discovery_scores,
            migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="discoveryscore",
            options={},
        ),
        migrations.RemoveField(
            model_name="discoveryscore",
            name="DSC_IS_CURRENT",
        ),
        migrations.AlterField(
            model_name="discoveryscore",
            name="BUSN_ID",
            field=models.OneToOneField(
                db_column="BUSN_ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discovery_score",
                to="business.business",
            ),
        ),
        migrations.AlterField(
            model_name="discoveryscore",
            name="DSC_D_SCORE",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="discoveryscore",
            name="DSC_S_SCORE",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="discoveryscore",
            name="DSC_V_SCORE",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryscore",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "DSC_S_SCORE__gte",
                        Decimal("0.00"),
                    ),
                    (
                        "DSC_S_SCORE__lte",
                        Decimal("1.00"),
                    ),
                ),
                name="discovery_specialty_score_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryscore",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "DSC_V_SCORE__gte",
                        Decimal("0.00"),
                    ),
                    (
                        "DSC_V_SCORE__lte",
                        Decimal("1.00"),
                    ),
                ),
                name="discovery_visibility_gap_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryscore",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "DSC_D_SCORE__gte",
                        Decimal("0.00"),
                    ),
                    (
                        "DSC_D_SCORE__lte",
                        Decimal("1.00"),
                    ),
                ),
                name="discovery_score_in_range",
            ),
        ),
    ]
