# Generated by Django 6.0.6 on 2026-09-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_alter_discoveryscore_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtytag',
            name='TAG_ICON',
            field=models.CharField(choices=[('tag', 'Tag'), ('star', 'Star'), ('heart', 'Heart'), ('sparkles', 'Sparkles'), ('badge_check', 'Badge Check'), ('circle_check', 'Check'), ('thumbs_up', 'Thumbs Up'), ('utensils', 'Utensils'), ('chef_hat', 'Chef Hat'), ('cooking_pot', 'Cooking Pot'), ('coffee', 'Coffee'), ('cup_soda', 'Drink'), ('cake_slice', 'Cake'), ('cupcake', 'Cupcake'), ('croissant', 'Croissant'), ('cookie', 'Cookie'), ('ice_cream_bowl', 'Ice Cream'), ('pizza', 'Pizza'), ('sandwich', 'Sandwich'), ('soup', 'Soup'), ('salad', 'Salad'), ('beef', 'Beef'), ('fish', 'Fish'), ('egg', 'Egg'), ('milk', 'Milk'), ('wheat', 'Wheat'), ('apple', 'Apple'), ('banana', 'Banana'), ('cherry', 'Cherry'), ('citrus', 'Citrus'), ('popcorn', 'Popcorn'), ('wine', 'Wine'), ('beer', 'Beer'), ('martini', 'Martini'), ('palette', 'Palette'), ('paintbrush', 'Paintbrush'), ('brush', 'Brush'), ('paint_bucket', 'Paint Bucket'), ('pencil', 'Pencil'), ('pen_tool', 'Pen Tool'), ('feather', 'Feather'), ('scissors', 'Scissors'), ('camera', 'Camera'), ('image', 'Image'), ('film', 'Film'), ('clapperboard', 'Clapperboard'), ('music', 'Music'), ('guitar', 'Guitar'), ('headphones', 'Headphones'), ('mic_vocal', 'Microphone'), ('radio', 'Radio'), ('ticket', 'Ticket'), ('drama', 'Theater'), ('gamepad_2', 'Gamepad'), ('book', 'Book'), ('book_open', 'Open Book'), ('library', 'Library'), ('graduation_cap', 'Graduation Cap'), ('newspaper', 'Newspaper'), ('leaf', 'Leaf'), ('sprout', 'Sprout'), ('tree_pine', 'Tree'), ('trees', 'Trees'), ('tree_palm', 'Palm Tree'), ('flower_2', 'Flower'), ('mountain', 'Mountain'), ('waves', 'Waves'), ('sun', 'Sun'), ('sunset', 'Sunset'), ('bike', 'Bike'), ('footprints', 'Walking'), ('compass', 'Compass'), ('binoculars', 'Binoculars'), ('map', 'Map'), ('map_pin', 'Map Pin'), ('route', 'Route'), ('navigation', 'Navigation'), ('shopping_bag', 'Shopping Bag'), ('shopping_basket', 'Shopping Basket'), ('shopping_cart', 'Shopping Cart'), ('store', 'Store'), ('gift', 'Gift'), ('shirt', 'Shirt'), ('gem', 'Gem'), ('heart_pulse', 'Heart Pulse'), ('dumbbell', 'Dumbbell'), ('trophy', 'Trophy'), ('activity', 'Activity'), ('house', 'House'), ('building_2', 'Building'), ('hotel', 'Hotel'), ('bed_double', 'Bed'), ('landmark', 'Landmark'), ('church', 'Church'), ('car', 'Car'), ('bus', 'Bus'), ('plane', 'Plane'), ('ship', 'Ship'), ('sailboat', 'Sailboat'), ('train_front', 'Train'), ('anchor', 'Anchor'), ('paw_print', 'Paw Print'), ('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird')], default='tag', max_length=50),
        ),
    ]
