# Generated by Django 6.0.6 on 2026-09-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_specialtytag_tag_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterDiscoveryShortcut',
            fields=[
                ('CDS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CDS_TITLE', models.CharField(max_length=100)),
                ('CDS_SUBTITLE', models.CharField(max_length=200)),
                ('CDS_IS_ACTIVE', models.BooleanField(default=True)),
                ('CDS_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('CDS_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('CLUS_ID', models.OneToOneField(db_column='CLUS_ID', on_delete=django.db.models.deletion.CASCADE, related_name='discovery_shortcut', to='business.cluster')),
            ],
            options={
                'db_table': 'CLUSTER_DISCOVERY_SHORTCUT',
            },
        ),
    ]
