# Generated by Django 6.0.6 on 2026-10-04 09:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NOTF_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NOTF_TYPE', models.CharField(max_length=64)),
                ('NOTF_TITLE', models.CharField(max_length=160)),
                ('NOTF_BODY', models.TextField(max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('NOTF_TARGET_TYPE', models.CharField(blank=True, default='', max_length=64)),
                ('NOTF_TARGET_ID', models.PositiveBigIntegerField(blank=True, null=True)),
                ('NOTF_DEDUP_KEY', models.CharField(max_length=160)),
                ('NOTF_READ_AT', models.DateTimeField(blank=True, null=True)),
                ('NOTF_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('NOTF_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NOTIFICATION',
                'ordering': ['-NOTF_CREATED_AT', '-NOTF_ID'],
                'indexes': [models.Index(fields=['USER_ID', '-NOTF_CREATED_AT', '-NOTF_ID'], name='notification_recipient_time'), models.Index(fields=['USER_ID', 'NOTF_READ_AT'], name='notification_recipient_read')],
                'constraints': [models.UniqueConstraint(fields=('USER_ID', 'NOTF_DEDUP_KEY'), name='notification_recipient_event'), models.CheckConstraint(condition=models.Q(models.Q(('NOTF_TARGET_ID__isnull', True), ('NOTF_TARGET_TYPE', '')), models.Q(models.Q(('NOTF_TARGET_TYPE', ''), _negated=True), ('NOTF_TARGET_ID__gt', 0), ('NOTF_TARGET_ID__isnull', False)), _connector='OR'), name='notification_target_pair')],
            },
        ),
    ]
