# Generated by Django 6.0.6 on 2026-08-24 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_businesspocket'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('USER_ID', 'BUSN_ID'), name='unique_user_business_review'),
        ),
    ]
