# Generated by Django 6.0.6 on 2026-08-25 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_unique_user_business_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyPhoto',
            fields=[
                ('RPHO_ID', models.AutoField(primary_key=True, serialize=False)),
                ('RPHO_PHOTO_URL', models.URLField()),
                ('RPHO_PHOTO_PUBLIC_ID', models.CharField(max_length=255)),
                ('RPLY_ID', models.ForeignKey(db_column='RPLY_ID', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reviews.reviewreply')),
            ],
            options={
                'db_table': 'REVIEW_REPLY_PHOTO',
            },
        ),
    ]
