# Generated by Django 6.0.6 on 2026-08-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_alter_business_busn_contact_number'),
        ('reviews', '0004_reviewreport_unique_user_review_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('RTPL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('RTPL_TITLE', models.CharField(max_length=100)),
                ('RTPL_TEXT', models.TextField(max_length=1000)),
                ('RTPL_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('RTPL_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='reply_templates', to='business.business')),
            ],
            options={
                'db_table': 'REVIEW_REPLY_TEMPLATE',
                'ordering': ['-RTPL_CREATED_AT'],
            },
        ),
    ]
