# Generated by Django 6.0.6 on 2026-09-20 13:02

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_clusterdiscoveryshortcut'),
        ('reviews', '0005_replytemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReviewSummary',
            fields=[
                ('BRSU_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BRSU_POSITIVE_COUNT', models.PositiveIntegerField(default=0)),
                ('BRSU_NEUTRAL_COUNT', models.PositiveIntegerField(default=0)),
                ('BRSU_NEGATIVE_COUNT', models.PositiveIntegerField(default=0)),
                ('BRSU_REVIEW_COUNT', models.PositiveIntegerField(default=0)),
                ('BRSU_CLASSIFIED_REVIEW_COUNT', models.PositiveIntegerField(default=0)),
                ('BRSU_KEYWORD_TAGS', models.JSONField(blank=True, default=list)),
                ('BRSU_SENTIMENT_COMPUTED_AT', models.DateTimeField(blank=True, null=True)),
                ('BRSU_KEYWORDS_PROCESSED_AT', models.DateTimeField(blank=True, null=True)),
                ('BRSU_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('BRSU_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.OneToOneField(db_column='BUSN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='review_summary', to='business.business')),
            ],
            options={
                'db_table': 'BUSINESS_REVIEW_SUMMARY',
                'constraints': [models.CheckConstraint(condition=models.Q(('BRSU_CLASSIFIED_REVIEW_COUNT', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('BRSU_POSITIVE_COUNT'), '+', models.F('BRSU_NEUTRAL_COUNT')), '+', models.F('BRSU_NEGATIVE_COUNT')))), name='brsu_classified_matches_counts'), models.CheckConstraint(condition=models.Q(('BRSU_CLASSIFIED_REVIEW_COUNT__lte', models.F('BRSU_REVIEW_COUNT'))), name='brsu_classified_lte_reviews')],
            },
        ),
    ]
