# Generated by Django 6.0.6 on 2026-09-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_businessreviewsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreviewsummary',
            name='BRSU_KEYWORDS_ATTEMPTED_AT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessreviewsummary',
            name='BRSU_KEYWORDS_FINGERPRINT',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='businessreviewsummary',
            name='BRSU_KEYWORDS_RETRYABLE',
            field=models.BooleanField(default=False),
        ),
    ]
