# Generated by Django 6.0.6 on 2026-09-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActivity",
            fields=[
                (
                    "AACT_ID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "AACT_ACTION",
                    models.CharField(
                        choices=[
                            ("user_suspended", "User suspended"),
                            ("user_reactivated", "User reactivated"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "AACT_CONTEXT",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "AACT_CREATED_AT",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "ACTOR_ID",
                    models.ForeignKey(
                        db_column="ACTOR_USER_ID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "TARGET_USER_ID",
                    models.ForeignKey(
                        db_column="TARGET_USER_ID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ADMIN_ACTIVITY",
                "ordering": ["-AACT_CREATED_AT", "-AACT_ID"],
                "indexes": [
                    models.Index(
                        fields=["TARGET_USER_ID", "-AACT_CREATED_AT"],
                        name="admin_activity_target_time",
                    ),
                ],
            },
        ),
    ]
