# Generated by Django 6.0.6 on 2026-09-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='AACT_ACTION',
            field=models.CharField(choices=[('admin_created', 'Admin created'), ('user_suspended', 'User suspended'), ('user_reactivated', 'User reactivated')], max_length=40),
        ),
    ]
