# Generated by Django 6.0.6 on 2026-10-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='AACT_ACTION',
            field=models.CharField(choices=[('user_suspended', 'User suspended'), ('user_reactivated', 'User reactivated'), ('review_dispute_upheld', 'Review dispute upheld'), ('review_dispute_dismissed', 'Review dispute dismissed')], max_length=40),
        ),
    ]
