# Generated by Django 6.0.6 on 2026-10-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_management', '0003_alter_adminactivity_aact_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='AACT_ACTION',
            field=models.CharField(choices=[('admin_created', 'Admin created'), ('user_suspended', 'User suspended'), ('user_reactivated', 'User reactivated'), ('review_dispute_upheld', 'Review dispute upheld'), ('review_dispute_dismissed', 'Review dispute dismissed'), ('review_report_approved', 'Review report approved'), ('review_report_rejected', 'Review report rejected')], max_length=40),
        ),
    ]
