# Generated by Django 6.0.6 on 2026-10-02 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0027_clusterdiscoveryshortcut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNameChangeRequest',
            fields=[
                ('BNCR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BNCR_PREVIOUS_BUSINESS_NAME', models.CharField(max_length=150)),
                ('BNCR_PROPOSED_BUSINESS_NAME', models.CharField(max_length=150)),
                ('BNCR_STATUS', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('BNCR_SUBMITTED_AT', models.DateTimeField()),
                ('BNCR_RESOLVED_AT', models.DateTimeField(blank=True, null=True)),
                ('BNCR_REJECTION_REASON', models.TextField(blank=True, null=True)),
                ('BNCR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('BNCR_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.PROTECT, related_name='name_change_requests', to='business.business')),
                ('REVIEWER_ID', models.ForeignKey(blank=True, db_column='REVIEWER_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_name_changes_reviewed', to=settings.AUTH_USER_MODEL)),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='business_name_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BUSINESS_NAME_CHANGE_REQUEST',
                'ordering': ['-BNCR_SUBMITTED_AT', '-BNCR_ID'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('BNCR_STATUS', 'pending')), fields=('BUSN_ID',), name='unique_pending_business_name_change')],
            },
        ),
    ]
