# Generated by Django 6.0.6 on 2026-10-03 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_clusterdiscoveryshortcut'),
        ('business_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClassificationChangeRequest',
            fields=[
                ('BCCR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BCCR_PREVIOUS_CATEGORY_NAME', models.CharField(max_length=100)),
                ('BCCR_PREVIOUS_CLUSTER_ID', models.PositiveIntegerField()),
                ('BCCR_PREVIOUS_CLUSTER_NAME', models.CharField(max_length=100)),
                ('BCCR_PROPOSED_CATEGORY_NAME', models.CharField(max_length=100)),
                ('BCCR_PROPOSED_CLUSTER_ID', models.PositiveIntegerField()),
                ('BCCR_PROPOSED_CLUSTER_NAME', models.CharField(max_length=100)),
                ('BCCR_STATUS', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('BCCR_SUBMITTED_AT', models.DateTimeField()),
                ('BCCR_RESOLVED_AT', models.DateTimeField(blank=True, null=True)),
                ('BCCR_REJECTION_REASON', models.TextField(blank=True, null=True)),
                ('BCCR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('BCCR_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.PROTECT, related_name='classification_change_requests', to='business.business')),
                ('PREVIOUS_CTGRY_ID', models.ForeignKey(db_column='PREVIOUS_CTGRY_ID', on_delete=django.db.models.deletion.PROTECT, related_name='previous_classification_requests', to='business.category')),
                ('PROPOSED_CTGRY_ID', models.ForeignKey(db_column='PROPOSED_CTGRY_ID', on_delete=django.db.models.deletion.PROTECT, related_name='proposed_classification_requests', to='business.category')),
                ('REVIEWER_ID', models.ForeignKey(blank=True, db_column='REVIEWER_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_classification_changes_reviewed', to=settings.AUTH_USER_MODEL)),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='business_classification_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BUSINESS_CLASSIFICATION_CHANGE_REQUEST',
                'ordering': ['-BCCR_SUBMITTED_AT', '-BCCR_ID'],
            },
        ),
        migrations.CreateModel(
            name='BusinessClassificationSpecialtySnapshot',
            fields=[
                ('BCSS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BCSS_SIDE', models.CharField(choices=[('previous', 'Previous'), ('proposed', 'Proposed')], max_length=10)),
                ('BCSS_TAG_NAME', models.CharField(max_length=100)),
                ('BCCR_ID', models.ForeignKey(db_column='BCCR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='specialty_snapshots', to='business_profile.businessclassificationchangerequest')),
                ('TAG_ID', models.ForeignKey(db_column='TAG_ID', on_delete=django.db.models.deletion.PROTECT, related_name='classification_request_snapshots', to='business.specialtytag')),
            ],
            options={
                'db_table': 'BUSINESS_CLASSIFICATION_SPECIALTY_SNAPSHOT',
                'ordering': ['BCSS_SIDE', 'TAG_ID_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessclassificationchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('BCCR_STATUS', 'pending')), fields=('BUSN_ID',), name='unique_pending_business_classification_change'),
        ),
        migrations.AddConstraint(
            model_name='businessclassificationspecialtysnapshot',
            constraint=models.UniqueConstraint(fields=('BCCR_ID', 'BCSS_SIDE', 'TAG_ID'), name='unique_classification_snapshot_tag'),
        ),
    ]
