# Generated by Django 6.0.6 on 2026-10-03 13:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_clusterdiscoveryshortcut'),
        ('business_profile', '0002_businessclassificationchangerequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocationChangeRequest',
            fields=[
                ('BLCR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BLCR_PREVIOUS_LOCT_ID', models.PositiveIntegerField()),
                ('BLCR_PREVIOUS_POINT', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('BLCR_PREVIOUS_ADDRESS', models.CharField(max_length=255)),
                ('BLCR_PREVIOUS_CITY', models.CharField(max_length=100)),
                ('BLCR_PREVIOUS_PROVINCE', models.CharField(max_length=100)),
                ('BLCR_PREVIOUS_POSTAL_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('BLCR_PROPOSED_POINT', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('BLCR_PROPOSED_ADDRESS', models.CharField(max_length=255)),
                ('BLCR_PROPOSED_CITY', models.CharField(max_length=100)),
                ('BLCR_PROPOSED_PROVINCE', models.CharField(max_length=100)),
                ('BLCR_PROPOSED_POSTAL_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('BLCR_STATUS', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('BLCR_SUBMITTED_AT', models.DateTimeField()),
                ('BLCR_RESOLVED_AT', models.DateTimeField(blank=True, null=True)),
                ('BLCR_REJECTION_REASON', models.TextField(blank=True, null=True)),
                ('BLCR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('BLCR_UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BUSN_ID', models.ForeignKey(db_column='BUSN_ID', on_delete=django.db.models.deletion.PROTECT, related_name='location_change_requests', to='business.business')),
                ('REVIEWER_ID', models.ForeignKey(blank=True, db_column='REVIEWER_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_location_changes_reviewed', to=settings.AUTH_USER_MODEL)),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='business_location_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BUSINESS_LOCATION_CHANGE_REQUEST',
                'ordering': ['-BLCR_SUBMITTED_AT', '-BLCR_ID'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLocationLandmarkSnapshot',
            fields=[
                ('BLLS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BLLS_SIDE', models.CharField(choices=[('previous', 'Previous'), ('proposed', 'Proposed')], max_length=10)),
                ('BLLS_PREVIOUS_BLMK_ID', models.PositiveIntegerField(blank=True, null=True)),
                ('BLLS_NAME', models.CharField(max_length=150)),
                ('BLLS_ADDRESS', models.CharField(max_length=255)),
                ('BLLS_POINT', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('BLLS_SOURCE', models.CharField(max_length=10)),
                ('BLLS_PLACE_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('BLCR_ID', models.ForeignKey(db_column='BLCR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='landmark_snapshots', to='business_profile.businesslocationchangerequest')),
            ],
            options={
                'db_table': 'BUSINESS_LOCATION_LANDMARK_SNAPSHOT',
                'ordering': ['BLLS_SIDE', 'BLLS_ID'],
            },
        ),
        migrations.AddConstraint(
            model_name='businesslocationchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('BLCR_STATUS', 'pending')), fields=('BUSN_ID',), name='unique_pending_business_location_change'),
        ),
    ]
