# Generated by Django 6.0.6 on 2026-10-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_profile", "0003_businesslocationchangerequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessclassificationchangerequest",
            name="BCCR_MERCHANT_REASON",
            field=models.CharField(max_length=500, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesslocationchangerequest",
            name="BLCR_MERCHANT_REASON",
            field=models.CharField(max_length=500, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessnamechangerequest",
            name="BNCR_MERCHANT_REASON",
            field=models.CharField(max_length=500, blank=True, null=True),
        ),
    ]
