from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def create_discovery_algorithm_configuration(
    apps,
    schema_editor,
):
    del schema_editor

    DiscoveryAlgorithmConfiguration = apps.get_model(
        "system_configuration",
        "DiscoveryAlgorithmConfiguration",
    )

    DiscoveryAlgorithmConfiguration.objects.get_or_create(
        DAC_ID=1,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscoveryAlgorithmConfiguration",
            fields=[
                (
                    "DAC_ID",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "DAC_SPECIALTY_SCORE_WEIGHT",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.80"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_VISIBILITY_GAP_WEIGHT",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.20"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_DECAY_RATE",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.10"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00001"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_VOUCH_ONLY_CONFIDENCE",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.70"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_VOUCH_REVIEW_CONFIDENCE",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.85"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_VOUCH_REVIEW_PHOTO_CONFIDENCE",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("1.00"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_REPUTATION_BASELINE",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_VOUCH_REPUTATION_REWARD",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_REVIEW_REPUTATION_REWARD",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_REVIEW_PHOTO_REPUTATION_REWARD",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_APPROVED_REPORT_REPUTATION_REWARD",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_CONFIRMED_VIOLATION_REPUTATION_PENALTY",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_VOUCH_ONLY_REPUTATION_CAP",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.40"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_MIN_CATEGORY_COMPARISON_SIZE",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "DAC_MIN_CLUSTER_COMPARISON_SIZE",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "DAC_VISIBILITY_WINDOW_DAYS",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "DAC_IMPRESSION_WEIGHT",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.60"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_PROFILE_VISIT_WEIGHT",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.20"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_SAVE_WEIGHT",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.20"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1.00"),
                            ),
                        ],
                    ),
                ),
                (
                    "DAC_CREATED_AT",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "DAC_UPDATED_AT",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
            ],
            options={
                "db_table": "DISCOVERY_ALGORITHM_CONFIGURATION",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("DAC_ID", 1)),
                        name=(
                            "discovery_algorithm_configuration_singleton"
                        ),
                    ),
                ],
            },
        ),
        migrations.RunPython(
            create_discovery_algorithm_configuration,
            migrations.RunPython.noop,
        ),
    ]
