# Generated by Django 6.0.6 on 2026-09-08 16:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def finalize_reputation_configuration(
    apps,
    schema_editor,
):
    del schema_editor

    DiscoveryAlgorithmConfiguration = apps.get_model(
        "system_configuration",
        "DiscoveryAlgorithmConfiguration",
    )

    DiscoveryAlgorithmConfiguration.objects.update_or_create(
        DAC_ID=1,
        defaults={
            "DAC_REPUTATION_BASELINE": Decimal("0.20"),
            "DAC_VOUCH_REPUTATION_REWARD": Decimal("0.01"),
            "DAC_REVIEW_REPUTATION_REWARD": Decimal("0.03"),
            "DAC_REVIEW_PHOTO_REPUTATION_REWARD": Decimal("0.05"),
            "DAC_APPROVED_REPORT_REPUTATION_REWARD": Decimal("0.02"),
            "DAC_CONFIRMED_VIOLATION_REPUTATION_PENALTY": (
                Decimal("0.10")
            ),
            "DAC_VOUCH_ONLY_REPUTATION_CAP": Decimal("0.40"),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "system_configuration",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.RunPython(
            finalize_reputation_configuration,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="discoveryalgorithmconfiguration",
            name="DAC_APPROVED_REPORT_REPUTATION_REWARD",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.02"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="discoveryalgorithmconfiguration",
            name="DAC_CONFIRMED_VIOLATION_REPUTATION_PENALTY",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.10"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="discoveryalgorithmconfiguration",
            name="DAC_REPUTATION_BASELINE",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.20"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="discoveryalgorithmconfiguration",
            name="DAC_REVIEW_PHOTO_REPUTATION_REWARD",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.05"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="discoveryalgorithmconfiguration",
            name="DAC_REVIEW_REPUTATION_REWARD",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.03"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="discoveryalgorithmconfiguration",
            name="DAC_VOUCH_REPUTATION_REWARD",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.01"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"),
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("1.00"),
                    ),
                ],
            ),
        ),
    ]
