# Generated by Django 6.0.6 on 2026-07-19 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('OAUTH_ID', models.AutoField(primary_key=True, serialize=False)),
                ('OAUTH_PROVIDER', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], max_length=20)),
                ('OAUTH_PROVIDER_ID', models.CharField(max_length=255)),
                ('OAUTH_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('OAUTH_LAST_LOGIN', models.DateTimeField(auto_now=True)),
                ('USER', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='OAUTH_ACCOUNTS', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_accounts',
                'constraints': [models.UniqueConstraint(fields=('OAUTH_PROVIDER', 'OAUTH_PROVIDER_ID'), name='unique_oauth_provider_account')],
            },
        ),
    ]
