# Generated by Django 6.0.6 on 2026-07-19 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='oauthaccount',
            constraint=models.UniqueConstraint(fields=('USER', 'OAUTH_PROVIDER'), name='unique_user_provider'),
        ),
    ]
