# Generated by Django 6.0.6 on 2026-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_oauthaccount_unique_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccount',
            name='OAUTH_AVATAR_URL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
